---
driver:
  name: vagrant
  customize:
    createhd:
      filename: smalldisk.vmdk
      size: 128
    storageattach:
      storagectl: SATA Controller
      port: 1
      device: 0
      type: hdd
      medium: smalldisk.vmdk


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    file_staging_uses_destdir: true

verifier:
  name: inspec

platforms:
#  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[tmp-test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
